#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "\033[32mBuilding the project...\033[0m"

make

echo -e "\033[32mChecking the code...\033[0m"

if elm-format src --validate; then
    echo -e "\033[32mPassed\033[0m"
else
    echo -e "\033[31mFailed, please run \"make format\" before you commit!\033[0m"
    exit 255
fi

python tools/formatdoc.py ./src --validate
